export const ThemeTypes = {
    name: 'string',
    dark: false,
    variables: {},
    colors: {
        primary: '',
        secondary: '',
        info: '',
        success: '',
        accent: '',
        warning: '',
        error: '',
        lightprimary: '',
        lightsecondary: '',
        lightsuccess: '',
        lighterror: '',
        lightinfo: '',
        lightwarning: '',
        textPrimary: '',
        textSecondary: '',
        borderColor: '',
        hoverColor: '',
        inputBorder: '',
        containerBg: '',
        surface: '',
        'on-surface-variant': '',
        grey100: '',
        grey200: '',
        muted: '',
    },
};
